---
defaults:
  - _self_

data_root: ${dataset.workdir}
epochs: 1
val_freq: 1
device: cpu
max_state_dim: 10
model:
  _target_: lib.models.transformer.AlgorithmDistillationTransformer
  state_max_dim: ${train.max_state_dim}
  action_max_dim: 10
  # num_tasks: 1
optimizer:
  _target_: torch.optim.Adam
  lr: 0.001
  weight_decay: 0.0
  amsgrad: false
loss:
  _target_: torch.nn.MSELoss
  reduction: mean
