---
defaults:
  - _self_

data_root: ${dataset.workdir}
epochs: 100
val_freq: 10
device: cpu
max_state_dim: 30
max_action_dim: 3
model:
  _target_: lib.models.transformer.AlgorithmDistillationTransformer
  state_dim: ${train.max_state_dim}
  action_dim: ${train.max_action_dim}
  d_model: 32
  num_layers: 2
  nhead: 4
  max_seq_len: 50
  num_tasks: 12
optimizer:
  _target_: torch.optim.Adam
  lr: 0.0001
  weight_decay: 0.01
  betas: [0.9, 0.98]
scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  T_max: 10
  eta_min: 1.0e-5
loss:
  _target_: torch.nn.MSELoss
  reduction: mean
