ncg:
  env_class: lib.envs.ncg.NCGEnv
  env_name: NCG
  params:
    initial_capital:
      _target_: lib.utils.clipped_exponential
      scale: 1
      low: 0.5
      high: 1.5
    deprecation:
      _target_: numpy.random.uniform
      low: 0.01
      high: 0.8

