defaults:
  - envs:
      - rbc
      - ncg
      - rbc_economy_with_policy
      - rbc_priority_based_weighted_contract
  - _self_

workdir: ${metadata.workdir}/dataset
enabled: True
train:
  type: dynare
  dynare_output_path: ???
val:
  type: dynare
  dynare_output_path: ???
  # type: envs
  # envs:
  #   - env_name: rbc
  #     num_steps: 1000
  #     num_combinations: 20
  #   - env_name: ncg
  #     num_steps: 1000
  #     num_combinations: 20
test:
  type: envs
  envs:
    - env_name: rbc
      num_steps: 1000
      num_combinations: 20
    - env_name: ncg
      num_steps: 1000
      num_combinations: 20
