defaults:
  - envs:
    - rbc
    - ncg
    - rbc_economy_with_policy
    - rbc_priority_based_weighted_contract
  - _self_

workdir: ${metadata.workdir}/dataset
train:
  envs:
    - env_name: rbc
      num_steps: 100
      num_combinations: 2
    - env_name: ncg
      num_steps: 100
      num_combinations: 2
    - env_name: rbc_economy_with_policy
      num_steps: 100
      num_combinations: 2
val:
  envs:
    - env_name: rbc
      num_steps: 100
      num_combinations: 1
#    - env_name: rbc_priority_based_weighted_contract
#      num_steps: 100
#      num_combinations: 1
test:
  envs:
    - env_name: rbc
      num_steps: 100
      num_combinations: 1
