save_dir: "./experiment/"

ablation:
  use_ablate: false

# Data Ingestion -------------------
data:
  file_type: "jsonl"
  path: "lora_tasks.jsonl"
  prompt:
    >- # prompt, make sure column inputs are enclosed in {} brackets and that they match your data
    Below is an description for the economic task. 
    Write the solution to the task. 
    ### Input: {input}
    ### Output:
  prompt_stub:
    >- # Stub to add for training at the end of prompt, for test set or inference, this is omitted; make sure only one variable is present
    {output}
  test_size: 0.1 # Proportion of test as % of total; if integer then # of samples
  train_size: 0.9 # Proportion of train as % of total; if integer then # of samples
  train_test_split_seed: 42

# Model Definition -------------------
model:
  hf_model_ckpt: "NousResearch/Llama-2-7b-hf"
  torch_dtype: "bfloat16"
  #attn_implementation: "flash_attention_2"
  quantize: true
  bitsandbytes:
    load_in_4bit: true
    bnb_4bit_compute_dtype: "bfloat16"
    bnb_4bit_quant_type: "nf4"

# LoRA Params -------------------
lora:
  task_type: "CAUSAL_LM"
  r: 32
  lora_alpha: 64
  lora_dropout: 0.1
  target_modules: "all-linear"
  # to target specific modules
  # target_modules:
  #   - q_proj
  #   - v_proj
  #   - k_proj
  #   - o_proj
  #   - up_proj
  #   - down_proj
  #   - gate_proj

# Training -------------------
training:
  training_args:
    num_train_epochs: 20000
    per_device_train_batch_size: 2
    gradient_accumulation_steps: 1
    gradient_checkpointing: True
    optim: "paged_adamw_32bit"
    logging_steps: 1
    learning_rate: 2.0e-4
    bf16: true # [Ampere+] Set to true for mixed precision training on Newer GPUs
    tf32: true # [Ampere+] Set to true for mixed precision training on Newer GPUs
    # fp16: false     # Set to true for mixed precision training on Older GPUs
    max_grad_norm: 0.3
    warmup_ratio: 0.03
    lr_scheduler_type: "constant"
  sft_args:
    max_seq_length: 1024
    # neftune_noise_alpha: None

inference:
  max_new_tokens: 256
  use_cache: True
  do_sample: True
  top_p: 0.9
  temperature: 0.8

qa:
  llm_metrics:
    - jaccard_similarity
    - dot_product
    - rouge_score
    - word_overlap
    - verb_percent
    - adjective_percent
    - noun_percent
    - summary_length
