---
defaults:
  - dataset: default
  - train: default
  - _self_
  
  - override hydra/launcher: basic

metadata:
  run_id: null # set by the pipeline
  seed: 42
  output_dir: ???
  workdir: ${.output_dir}/${.run_id}
  entity: lexolord-innopolis-university
  project: marl-macro
  track: false
